name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip
          pip install buildozer cython virtualenv

      - name: Initialize Buildozer
        run: |
          buildozer init || true

      - name: Update buildozer.spec requirements
        run: |
          # Sửa dòng requirements, thêm các thư viện cần thiết như kivy, requests, Pillow
          sed -i 's/requirements = python3/requirements = python3,kivy,requests,Pillow/g' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: List bin directory
        run: |
          ls -la bin/

      - name: Prepare artifact
        run: |
          mkdir -p apk_output
          mv bin/*.apk apk_output/ || echo "No APK found!"

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: JJDL-APK
          path: apk_output/*.apk
