name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          # Khởi tạo buildozer.spec (nếu cần)
          # Nếu bạn đã có buildozer.spec rồi, có thể bỏ qua lệnh init
          buildozer init

          # Sửa buildozer.spec nếu cần (hoặc chỉnh bằng lệnh sed)
          # buildozer.spec sẽ có sẵn "requirements = python3,kivy"
          # => Thêm thư viện bạn dùng, ví dụ requests, pillow, v.v...
          # Dưới đây chỉ là ví dụ, bạn có thể tự chỉnh
          sed -i 's/requirements = python3/requirements = python3,kivy,requests,Pillow/g' buildozer.spec

          # Build APK
          buildozer -v android debug

          # Tạo thư mục output & chuyển file apk vào
          mkdir -p apk_output
          mv bin/*.apk apk_output/

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: JJDL-APK
          path: apk_output/*.apk
